class Tags:
    ADJ = "ADJ"  # adjective
    ADP = "ADP"  # adposition
    ADV = "ADV"  # adverb
    AUX = "AUX"  # auxiliary
    CONJ = "CONJ"  # conjunction
    CCONJ = "CCONJ"  # coordinating conjunction
    DET = "DET"  # determiner
    INTJ = "INTJ"  # interjection
    NOUN = "NOUN"  # noun
    NUM = "NUM"  # numeral
    PART = "PART"  # particle
    PRON = "PRON"  # pronoun
    PROPN = "PROPN"  # proper noun
    PUNCT = "PUNCT"  # punctuation
    SCONJ = "SCONJ"  # subordinating conjunction
    SYM = "SYM"  # symbol
    VERB = "VERB"  # verb
    X = "X"  # other
    SPACE = "SPACE"  # space


class Dependencies:
    ACL = "acl"  # Clausal modifier of noun
    ACOMP = "acomp"  # Adjectival complement
    ADVCL = "advcl"  # Adverbial clause modifier
    ADVMOD = "advmod"  # Adverbial modifier
    AGENT = "agent"  # Agent
    AMOD = "amod"  # Adjectival modifier
    APPOS = "appos"  # Appositional modifier
    ATTR = "attr"  # Attribute
    AUX = "aux"  # Auxiliary
    AUXPASS = "auxpass"  # Auxiliary (passive)
    CASE = "case"  # Case marker
    CC = "cc"  # Coordinating conjunction
    CCOMP = "ccomp"  # Clausal complement
    COMPOUND = "compound"  # Compound modifier
    CONJ = "conj"  # Conjunct
    CSUBJ = "csubj"  # Clausal subject
    CSUBJPASS = "csubjpass"  # Clausal subject (passive)
    DATIVE = "dative"  # Dative
    DEP = "dep"  # Unclassified dependent
    DET = "det"  # Determiner
    DOBJ = "dobj"  # Direct Object
    EXPL = "expl"  # Expletive
    INTJ = "intj"  # Interjection
    MARK = "mark"  # Marker
    META = "meta"  # Meta modifier
    NEG = "neg"  # Negation modifier
    NOUNMOD = "nounmod"  # Modifier of nominal
    NPMOD = "npmod"  # Noun phrase as adverbial modifier
    NSUBJ = "nsubj"  # Nominal subject
    NSUBJPASS = "nsubjpass"  # Nominal subject (passive)
    NUMMOD = "nummod"  # Number modifier
    OPRD = "oprd"  # Object predicate
    PARATAXIS = "parataxis"  # Parataxis
    PCOMP = "pcomp"  # Complement of preposition
    POBJ = "pobj"  # Object of preposition
    POSS = "poss"  # Possession modifier
    PRECONJ = "preconj"  # Pre-correlative conjunction
    PREDET = "predet"  # Pre-determiner
    PREP = "prep"  # Prepositional modifier
    PRT = "prt"  # Particle
    PUNCT = "punct"  # Punctuation
    QUANTMOD = "quantmod"  # Modifier of quantifier
    RELCL = "relcl"  # Relative clause modifier
    ROOT = "ROOT"  # Root
    XCOMP = "xcomp"  # Open clausal complement
